apiVersion: v1
kind: Secret
metadata:
  name: arrs-secrets
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:VpeI4U16RqHgUOQ2anzM80+1gSvt049fGKtvc/afUkw=,iv:SVkqXMrsfQIm7S4N807NAczjmpsdPfAm+++jltHeKr0=,tag:LG0YXa0DQF8WQHsnlfDzqg==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:XeQBx2g068qrHvRKA2rGfAQ9FVOQzKUmjwzhVH6CC3k=,iv:peUlCyDBWVUz2g+7nLkah4V7C8wMdBS7z/p4CMhIBo0=,tag:/WENoUxYORZpyKyxgjWitQ==,type:str]
  SABNZBD_API_KEY: ENC[AES256_GCM,data:GTVZY8GYKg4Jd0o1isl7stThHN2kGY79fYFvGp8HEwM=,iv:XiawSDa5yO48pM+vPMIAxhwj+aVUs2yUCpVQBK5Ipgs=,tag:Yi+mxjcydCP2Eai0zAuYUw==,type:str]
  BAZARR_API_KEY: null
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ft4dldx5zezaajkju2gsaugvtqqhvughw3hw29ekl7qvdcukfq3spcfntq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6T0orY3FiYmxmSVJPSTlp
        dFRrd2xhRFlzVENyK044NVF3UStqei8rMmlrCnJkQ2o2NTlSVnBHS0hQZURlb01O
        V1hXWHdQdGc5aHRqWjMvMmcra1IxcEEKLS0tIGZ4M2NuaENpejhINjlJRkdPeGhT
        Q1dmTlJERDFwdEdjakJyMzFVWUFHYzAKFmNCwwAkoLUinzZZa0Z3QcI7DhAcEchr
        IaFFeDBYfOyQjFzTZk4jOMbaJcrPbOGn3Z/QasC/0ahLrd5i+3XYHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T17:14:57Z"
  mac: ENC[AES256_GCM,data:v/E1TsKzYbc4BidIN7YTLTy1I0JFSML+iVWXGaEF123cAVW9XvSLOHbh+cRRERmlqD0UJUdhx9FU6TjL85RQAuO5wGXpb0EHL1sVeXTeBOb3b+hsC4bwbvR2/oDFClfYqp5Nx3if3bIksVQWEtmYWtDdSW5vp5xU8h8PbVjcgYY=,iv:ga0UYvf+GQCaeMyMFu1c7WNt82DUcgJ/E91N22AL8uw=,tag:9ZK+DRcQ8dj9XqVqSd3LNg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
