---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: 2.10.2
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  install:
    crds: Create  # Ensures CRDs are installed
  upgrade:
    crds: CreateReplace  # Updates CRDs on upgrade
  #dependsOn:
  #  - name: ingress-nginx-external
  #    namespace: networking
  dependsOn:
    - name: ingress-nginx
      namespace: networking
  values:
    replicas: 3
    hostname: rancher.${SECRET_DOMAIN}
    tls: ingress
    ingress:
      #ingressClassName: nginx-external
      ingressClassName: nginx
      extraAnnotations:
        #external-dns.alpha.kubernetes.io/target: "${SECRET_GATEWAY}"
        kubernetes.io/tls-acme: "true"
        #nginx.ingress.kubernetes.io/auth-url: http://authelia.networking.svc.cluster.local/api/authz/auth-request
        #nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}
      tls:
        source: secret
        secretName: rancher-tls
    bootstrapPassword: "${SECRET_RANCHER_ADMIN_PASSWORD}"
    extraEnv:
      - name: CATTLE_PASSWORD_MIN_LENGTH
        value: "12"  # Ensures the bootstrap password is at least 12 characters, prompting stronger passwords on reset