apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook-secret
stringData:
  address: ENC[AES256_GCM,data:2JJ9kEIzOHMwjhpUqgbQRwKCeQqN3t5FyDuPXh+PwRK+8rugOkxGfNU0HEaXOhfT7RQPng9T352eEPlILDgXVkeY1fuadVisFfjzclLx56SlrjRjVwk+ZlDYggn0UYqr2iI2IVd6QWgPcwjvky/FeFmYb1aRO7LlWA==,iv:VexTl2S6sTFZ89DCFqfSkhkDyOTI5ULhKwv51KmuqME=,tag:s0n2VA4a9f2PH0q3fNOJhQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ft4dldx5zezaajkju2gsaugvtqqhvughw3hw29ekl7qvdcukfq3spcfntq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyS1pDbDNtTUFlVW94K1Mv
        Z2JXd2hXMGlyN1UzYWs5RjNZNDZWMCtsZ1QwCnZjcmZKcUhBZWxMK2NoeWdmOXVm
        K3o2SjU5ZEZUOUVCbHFHRFBKRUNsWDgKLS0tIHZxRTVxMU5PR1JaV1pQeGw4aFlF
        bVFrWnlNQno5blVia2tjOWpZTXFGYncKu/ykhsqSUxChWfc081lWNRi+LQ7aQRK7
        wPq3UaeSd7nKskeY7SQHbOAvrUvQiF/pTz5R96XiLujAesfeZjuklQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-24T21:52:52Z"
  mac: ENC[AES256_GCM,data:5CAXy2owhFQHigeYPN8LNPPeDKNqPgHft0VEAp/SoR4AQvR5EVPBQWthMd809I687nYOMjq2GFTHnHYyH2tUgx0Teax24wSb5K48ehKgdZqOGdxtA79548NnrH53lKUUH0QWFho9dEQOcsTnvnJWeEuzFak3ly3adWxIAKGvOvs=,iv:T9paXYLgPA09X5i0yH4eIw/9GLApDAgtP4GGtSPDz4M=,tag:iEaVECRcRjR/Fm0EH05HbQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
