---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sabnzbd-app
  namespace: flux-system
spec:
  path: ./apps/sabnzbd
  targetNamespace: vpn
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
