apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:k+U+ftn4Xe85kZ/d,iv:H8DgwIet8PzJoNhF6sFZNDe8wYPSV71ZECeS8Tgj8ss=,tag:vlBq28iyGZz5/M6DS9DNWw==,type:str]
    SECRET_GATEWAY: ENC[AES256_GCM,data:4gbOPgjSraS1IiI=,iv:qCetdQFjYNm9SuQFkXo6+9DHxztm4b3uGSM4lripmac=,tag:qpGzO17PG0DOmHbb3DYYuw==,type:str]
    SECRET_CIFS_SHARE: ENC[AES256_GCM,data:o6ENlcc9hlKmPAmqasht8xs=,iv:qNd6qQ3hE5Rqnff5kn2jq2GYVeRWtqp6BoIh6IuAZg8=,tag:hkydhza332YkbvCysKIqCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ft4dldx5zezaajkju2gsaugvtqqhvughw3hw29ekl7qvdcukfq3spcfntq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVlVYdnd0UUkrRVRWQms5
            Z0hvN0pUay84c1hIc05TTGcxUWxwYndrRkNrCk1HOTUrbllrc21iU1AvMVM4S1Bk
            VnFuTEVjTWxUT2Vqc0NhSGtFemdvSUEKLS0tIFpaR3hyOE5LU3YxS1ZsdkpDRzFi
            Y3hNL3Z1QUtQYWx6b1BiczRldk5iem8KybnLaou9BAMucj1HPZ/Udz1cVvuRCG1g
            rU/KhoNTXvevCbCN1ZRMUSa5N2Ugw9tc9kOhy3XP+12xmKPHY8dDqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-01T21:32:16Z"
    mac: ENC[AES256_GCM,data:RRCoryjYpDWuPnC5WOgXvUAQHlfwIUQZ7bC2tm0YbiJ7ALCGul8mBriZPC0NEqVZ0Sgf0g3Zlcnsy8tYdxozllpTDyExzhgmFK0LjqpxLYrHhJGmF4IbbJM7EGIPR+IG+92vFyhXZ2YsM0FBazgMZkq+9FeN98WZoeC83CUso0o=,iv:4AL0ZX3RK2Vu3DCzHxqojZ1uOelj+JgDPgyUeBzx/4o=,tag:Xm1QpcmOQ57jyXIWavpT6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
