---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  #dependsOn:
  #  - name: minio
  #    namespace: selfhosted
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      reclaimPolicy: Delete
      recurringJobSelector:
        enable: false
      removeSnapshotsDuringFilesystemTrim: enabled
      dataEngine: v1
    ingress:
      enabled: true
      #ingressClassName: nginx-external
      ingressClassName: nginx
      annotations:
        #external-dns.alpha.kubernetes.io/target: "${SECRET_GATEWAY}"
        kubernetes.io/tls-acme: "true"
        #nginx.ingress.kubernetes.io/auth-url: http://authelia.networking.svc.cluster.local/api/authz/auth-request
        #nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}
      host: longhorn.${SECRET_DOMAIN}
      tls: true
      tlsSecret: longhorn-tls
    defaultSettings:
      defaultDataPath: "/var/mnt/longhorn"
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 10
      defaultLonghornStaticStorageClass: longhorn-backup
      restoreVolumeRecurringJobs: true
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      autoCleanupSystemGeneratedSnapshot: true
      autoCleanupRecurringJobBackupSnapshot: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      orphanAutoDeletion: true
      snapshotDataIntegrity: enabled
      snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: false
      snapshotDataIntegrityCronjob: "0 4 * * *"
      fastReplicaRebuildEnabled: true
      removeSnapshotsDuringFilesystemTrim: true
      v1DataEngine: true
      v2DataEngine: false
      allowCollectingLonghornUsageMetrics: false
      freezeFilesystemForSnapshot: true
      autoCleanupSnapshotWhenDeleteBackup: true
      rwxVolumeFastFailover: true
    tolerations:  # Added from Helm command
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    nodeSelector:  # Added from Helm command
      node-role.kubernetes.io/worker: ""
    podSecurityPolicy:  # Added from Helm command
      enabled: false
    global:
      securityContext:  # Added from Helm command
        runAsNonRoot: false
        allowPrivilegeEscalation: true
        capabilities:
          drop: []
        privileged: true
        seccompProfile:
          type: ""
    #defaultBackupStore:
    #  backupTarget: s3://longhorn@us-east-1/
    #  backupTargetCredentialSecret: longhorn-system-secrets
