---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: certificate-exporter
spec:
  interval: 5m
  chart:
    spec:
      chart: x509-certificate-exporter
      version: 3.18.1
      sourceRef:
        kind: HelmRepository
        name: enix-charts
        namespace: flux-system
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    secretsExporter:
      resources:
        limits:
          cpu: null
    hostPathsExporter:
      daemonSets:
        cp:  # Control plane nodes
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
          watchFiles:
            # Talos control plane certificates
            - /system/secrets/kubernetes/kube-apiserver.crt
            - /system/secrets/kubernetes/kube-controller-manager.crt
            - /system/secrets/kubernetes/kube-scheduler.crt
            - /system/secrets/kubernetes/etcd-client.crt
            - /system/secrets/kubernetes/etcd-peer.crt
            - /system/secrets/kubernetes/etcd-server.crt
            - /system/secrets/kubernetes/ca.crt
            - /system/secrets/kubernetes/front-proxy-ca.crt
            - /system/secrets/kubernetes/front-proxy-client.crt
        workers:  # Worker nodes
          watchFiles:
            # Talos worker node certificates
            - /system/secrets/kubernetes/kubelet.crt
            - /system/secrets/kubernetes/kubelet-client.crt
            - /system/secrets/kubernetes/ca.crt
      resources:
        limits:
          cpu: null