---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: default  # Adjust if different
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: ingress-nginx
      namespace: networking
    - name: csi-driver-smb
      namespace: kube-system
    - name: longhorn
      namespace: longhorn-system
  values:
    controllers:
      sabnzbd:
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/sabnzbd
              tag: latest@sha256:d5f659a45ba38b109b92bec00c080c192813b74a3bf66ed55dec51d8d95997cc
            env:
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
              - name: TZ
                value: "Etc/UTC"
    service:
      sabnzbd:
        controller: sabnzbd
        ports:
          http:
            port: 8080
    ingress:
      main:
        className: "nginx"
        annotations:
          kubernetes.io/tls-acme: "true"
        hosts:
        - host: sabnzbd.${SECRET_DOMAIN}
          paths:
          - path: /
            service:
              identifier: sabnzbd
              port: http
        tls:
        - secretName: "${SECRET_DOMAIN/./-}-tls"
          hosts:
          - "*.${SECRET_DOMAIN}"
    persistence:
      config:
        existingClaim: sabnzbd-data
        globalMounts:
          - path: "/config"
      downloads:
        existingClaim: arrs-downloads
        globalMounts:
          - path: "/downloads"