apiVersion: v1
kind: Secret
metadata:
  name: external-dns-cloudflare-secrets
stringData:
  cloudflare_api_token: ENC[AES256_GCM,data:NrpWYy/8r3HarYmzRf8gKKirp90pfyH4+sM5/Sw6ZwjbkbuNPgvhmA==,iv:tDXzXVRBvzxklC079Z77vvsD4ES/rJdU2tRzAmqnq44=,tag:i9+9t0OsRMN4GuK3W5n+xA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ft4dldx5zezaajkju2gsaugvtqqhvughw3hw29ekl7qvdcukfq3spcfntq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRjVUdHk4U2cySjBETWRP
        QXMycW1ETklJYVE0MnNhSWo1aDdwNTk5ZkdrCnhrMnQrNSszOTlsUVZkbHd4T01o
        dkVYSm5uaWVkN1c3MUNLTUJmc2F2RjQKLS0tIG52L081UjlOWFhGV3E1TFltL0tz
        aFVLcFFZQjhGS1E0OVdrN1gvYVF6SjQKooGyiKeDFXN7y7fIo6cuhhkBiPmACNY1
        kCQFuujMRMhTYUQtXg7DtCx70FtTjYSnezoYKqVEBEKdFB3kGJsr7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-24T22:02:23Z"
  mac: ENC[AES256_GCM,data:1Y4H3zJGS6TNuPPtpmyMoMNxvxgHB8wZpQw/4ZMgReYh1TQlCm2dZOR0eZokRudaVzkJ226Nfmv91xljS6UOQHgzm/RCOjjPuWocbWrpDUm2pNdXDYabmlBZ8hLn+HdM/I2fBNGslt+b9t6/aMfJssgaQZBMvXzxZExkJjCJYtU=,iv:C5ZyGEEvD07/WzeusywrQmZTP/RLc3DskWTkU7+lOTY=,tag:GviWHh7S9YBB3ds4otEf5Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
